name: Run Bale Bot

on:
  schedule:
    # هر ۶ ساعت یک‌بار
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg rar
    
    - name: Run bot
      env:
        BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        CHAT_ID_GROUP: ${{ secrets.CHAT_ID_GROUP }}
        ARCHIVE_PASSWORD: ${{ secrets.ARCHIVE_PASSWORD }}
        YOUTUBE_COOKIES_BASE64: ${{ secrets.YOUTUBE_COOKIES_BASE64 }}
      run: |
        python main.py
